// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { BulkDocsData, BulkDocsResponses, CreateDatabaseData, CreateDatabaseErrors, CreateDatabaseResponses, DeleteDatabaseData, DeleteDatabaseResponses, DeleteDocumentData, DeleteDocumentErrors, DeleteDocumentResponses, FindDocumentsData, FindDocumentsResponses, GetAllDocsData, GetAllDocsResponses, GetDatabaseInfoData, GetDatabaseInfoErrors, GetDatabaseInfoResponses, GetDocumentData, GetDocumentErrors, GetDocumentResponses, PostAllDocsData, PostAllDocsResponses, PutDocumentData, PutDocumentErrors, PutDocumentResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Delete a database
 */
export const deleteDatabase = <ThrowOnError extends boolean = false>(options: Options<DeleteDatabaseData, ThrowOnError>) => (options.client ?? client).delete<DeleteDatabaseResponses, unknown, ThrowOnError>({ url: '/{db}', ...options });

/**
 * Get database information
 */
export const getDatabaseInfo = <ThrowOnError extends boolean = false>(options: Options<GetDatabaseInfoData, ThrowOnError>) => (options.client ?? client).get<GetDatabaseInfoResponses, GetDatabaseInfoErrors, ThrowOnError>({ url: '/{db}', ...options });

/**
 * Create a database
 */
export const createDatabase = <ThrowOnError extends boolean = false>(options: Options<CreateDatabaseData, ThrowOnError>) => (options.client ?? client).put<CreateDatabaseResponses, CreateDatabaseErrors, ThrowOnError>({ url: '/{db}', ...options });

/**
 * Delete a document
 */
export const deleteDocument = <ThrowOnError extends boolean = false>(options: Options<DeleteDocumentData, ThrowOnError>) => (options.client ?? client).delete<DeleteDocumentResponses, DeleteDocumentErrors, ThrowOnError>({ url: '/{db}/{docid}', ...options });

/**
 * Get a document
 */
export const getDocument = <ThrowOnError extends boolean = false>(options: Options<GetDocumentData, ThrowOnError>) => (options.client ?? client).get<GetDocumentResponses, GetDocumentErrors, ThrowOnError>({ url: '/{db}/{docid}', ...options });

/**
 * Create or update a document
 */
export const putDocument = <ThrowOnError extends boolean = false>(options: Options<PutDocumentData, ThrowOnError>) => (options.client ?? client).put<PutDocumentResponses, PutDocumentErrors, ThrowOnError>({
    url: '/{db}/{docid}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all documents
 */
export const getAllDocs = <ThrowOnError extends boolean = false>(options: Options<GetAllDocsData, ThrowOnError>) => (options.client ?? client).get<GetAllDocsResponses, unknown, ThrowOnError>({ url: '/{db}/_all_docs', ...options });

/**
 * List documents with keys
 */
export const postAllDocs = <ThrowOnError extends boolean = false>(options: Options<PostAllDocsData, ThrowOnError>) => (options.client ?? client).post<PostAllDocsResponses, unknown, ThrowOnError>({
    url: '/{db}/_all_docs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Query documents using Mango selector
 */
export const findDocuments = <ThrowOnError extends boolean = false>(options: Options<FindDocumentsData, ThrowOnError>) => (options.client ?? client).post<FindDocumentsResponses, unknown, ThrowOnError>({
    url: '/{db}/_find',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Bulk document operations
 */
export const bulkDocs = <ThrowOnError extends boolean = false>(options: Options<BulkDocsData, ThrowOnError>) => (options.client ?? client).post<BulkDocsResponses, unknown, ThrowOnError>({
    url: '/{db}/_bulk_docs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
