// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3001' | (string & {});
};

export type OkResponse = {
    ok: true;
};

export type ErrorResponse = {
    error: string;
    reason: string;
};

export type DatabaseInfo = {
    db_name?: string;
    doc_count?: number;
    update_seq?: number;
};

export type Document = {
    _id?: string;
    _rev?: string;
    [key: string]: unknown | string | undefined;
};

export type DocumentInput = {
    /**
     * Required for updates
     */
    _rev?: string;
    [key: string]: unknown | string | undefined;
};

export type DocumentResponse = {
    ok: boolean;
    id: string;
    rev: string;
};

export type AllDocsResponse = {
    total_rows?: number;
    offset?: number;
    rows?: Array<{
        id?: string;
        key?: string;
        value?: {
            rev?: string;
        };
        doc?: Document;
    }>;
};

export type FindRequest = {
    /**
     * Mango selector
     */
    selector: {
        [key: string]: unknown;
    };
    fields?: Array<string>;
    limit?: number;
    skip?: number;
};

export type FindResponse = {
    docs?: Array<Document>;
};

export type BulkDocsRequest = {
    docs: Array<DocumentInput>;
};

export type BulkDocResult = {
    ok?: boolean;
    id?: string;
    rev?: string;
    error?: string;
    reason?: string;
};

/**
 * Database name
 */
export type DatabaseName = string;

/**
 * Document ID
 */
export type DocumentId = string;

export type DeleteDatabaseData = {
    body?: never;
    path: {
        /**
         * Database name
         */
        db: string;
    };
    query?: never;
    url: '/{db}';
};

export type DeleteDatabaseResponses = {
    /**
     * Database deleted
     */
    200: OkResponse;
};

export type DeleteDatabaseResponse = DeleteDatabaseResponses[keyof DeleteDatabaseResponses];

export type GetDatabaseInfoData = {
    body?: never;
    path: {
        /**
         * Database name
         */
        db: string;
    };
    query?: never;
    url: '/{db}';
};

export type GetDatabaseInfoErrors = {
    /**
     * Database not found
     */
    404: ErrorResponse;
};

export type GetDatabaseInfoError = GetDatabaseInfoErrors[keyof GetDatabaseInfoErrors];

export type GetDatabaseInfoResponses = {
    /**
     * Database info
     */
    200: DatabaseInfo;
};

export type GetDatabaseInfoResponse = GetDatabaseInfoResponses[keyof GetDatabaseInfoResponses];

export type CreateDatabaseData = {
    body?: never;
    path: {
        /**
         * Database name
         */
        db: string;
    };
    query?: never;
    url: '/{db}';
};

export type CreateDatabaseErrors = {
    /**
     * Database already exists
     */
    412: ErrorResponse;
};

export type CreateDatabaseError = CreateDatabaseErrors[keyof CreateDatabaseErrors];

export type CreateDatabaseResponses = {
    /**
     * Database created
     */
    201: OkResponse;
};

export type CreateDatabaseResponse = CreateDatabaseResponses[keyof CreateDatabaseResponses];

export type DeleteDocumentData = {
    body?: never;
    path: {
        /**
         * Database name
         */
        db: string;
        /**
         * Document ID
         */
        docid: string;
    };
    query: {
        /**
         * Current revision ID
         */
        rev: string;
    };
    url: '/{db}/{docid}';
};

export type DeleteDocumentErrors = {
    /**
     * Revision conflict
     */
    409: ErrorResponse;
};

export type DeleteDocumentError = DeleteDocumentErrors[keyof DeleteDocumentErrors];

export type DeleteDocumentResponses = {
    /**
     * Document deleted
     */
    200: DocumentResponse;
};

export type DeleteDocumentResponse = DeleteDocumentResponses[keyof DeleteDocumentResponses];

export type GetDocumentData = {
    body?: never;
    path: {
        /**
         * Database name
         */
        db: string;
        /**
         * Document ID
         */
        docid: string;
    };
    query?: never;
    url: '/{db}/{docid}';
};

export type GetDocumentErrors = {
    /**
     * Document not found
     */
    404: ErrorResponse;
};

export type GetDocumentError = GetDocumentErrors[keyof GetDocumentErrors];

export type GetDocumentResponses = {
    /**
     * Document found
     */
    200: Document;
};

export type GetDocumentResponse = GetDocumentResponses[keyof GetDocumentResponses];

export type PutDocumentData = {
    body: DocumentInput;
    path: {
        /**
         * Database name
         */
        db: string;
        /**
         * Document ID
         */
        docid: string;
    };
    query?: never;
    url: '/{db}/{docid}';
};

export type PutDocumentErrors = {
    /**
     * Revision conflict
     */
    409: ErrorResponse;
};

export type PutDocumentError = PutDocumentErrors[keyof PutDocumentErrors];

export type PutDocumentResponses = {
    /**
     * Document created/updated
     */
    201: DocumentResponse;
};

export type PutDocumentResponse = PutDocumentResponses[keyof PutDocumentResponses];

export type GetAllDocsData = {
    body?: never;
    path: {
        /**
         * Database name
         */
        db: string;
    };
    query?: {
        include_docs?: boolean;
        limit?: number;
        skip?: number;
    };
    url: '/{db}/_all_docs';
};

export type GetAllDocsResponses = {
    /**
     * Document list
     */
    200: AllDocsResponse;
};

export type GetAllDocsResponse = GetAllDocsResponses[keyof GetAllDocsResponses];

export type PostAllDocsData = {
    body?: {
        keys?: Array<string>;
        include_docs?: boolean;
    };
    path: {
        /**
         * Database name
         */
        db: string;
    };
    query?: never;
    url: '/{db}/_all_docs';
};

export type PostAllDocsResponses = {
    /**
     * Document list
     */
    200: AllDocsResponse;
};

export type PostAllDocsResponse = PostAllDocsResponses[keyof PostAllDocsResponses];

export type FindDocumentsData = {
    body: FindRequest;
    path: {
        /**
         * Database name
         */
        db: string;
    };
    query?: never;
    url: '/{db}/_find';
};

export type FindDocumentsResponses = {
    /**
     * Query results
     */
    200: FindResponse;
};

export type FindDocumentsResponse = FindDocumentsResponses[keyof FindDocumentsResponses];

export type BulkDocsData = {
    body: BulkDocsRequest;
    path: {
        /**
         * Database name
         */
        db: string;
    };
    query?: never;
    url: '/{db}/_bulk_docs';
};

export type BulkDocsResponses = {
    /**
     * Bulk operation results
     */
    201: Array<BulkDocResult>;
};

export type BulkDocsResponse = BulkDocsResponses[keyof BulkDocsResponses];
