
export const ERROR_CODES = {
    AUTH_MISSING_TCC: 'AUTH_MISSING_TCC',
    INVALID_EIN_FORMAT: 'INVALID_EIN_FORMAT',
    INVALID_PAYEE_TIN: 'INVALID_PAYEE_TIN',
    INVALID_TIN_FORMAT: 'INVALID_TIN_FORMAT',
    NO_PAYEES: 'NO_PAYEES',
    BATCH_TOO_LARGE: 'BATCH_TOO_LARGE',
    MISSING_TRANSMITTER_ID: 'MISSING_TRANSMITTER_ID',
    MISSING_FILER_EIN: 'MISSING_FILER_EIN',
    RECEIPT_NOT_FOUND: 'RECEIPT_NOT_FOUND',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
};

export const ERROR_MESSAGES = {
    [ERROR_CODES.INVALID_EIN_FORMAT]: 'EIN must be in format XX-XXXXXXX',
    [ERROR_CODES.INVALID_PAYEE_TIN]: 'TIN must be in format XX-XXXXXXX or XXX-XX-XXXX',
    [ERROR_CODES.INVALID_TIN_FORMAT]: 'Invalid TIN format. Expected XX-XXXXXXX for EIN or XXX-XX-XXXX for SSN.',
};
