/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/trusts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTrusts"];
        put?: never;
        /** Create trust */
        post: operations["createTrust"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trusts/{trustId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTrust"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update trust */
        patch: operations["updateTrust"];
        trace?: never;
    };
    "/trusts/{trustId}/trustees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List trustees */
        get: operations["listTrustees"];
        put?: never;
        /** Add trustee */
        post: operations["addTrustee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trusts/trustees/{trusteeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update trustee */
        patch: operations["updateTrustee"];
        trace?: never;
    };
    "/ledger/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chart of Accounts */
        get: operations["listAccounts"];
        put?: never;
        /** Add Account */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/journal-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Journal Entry (Draft) */
        post: operations["createJournalEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/journal-entries/{jeId}/post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Journal Entry (Finalize)
         * @description Skips "Approval" step. Directly posts if valid.
         */
        post: operations["postJournalEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAssets"];
        put?: never;
        post: operations["createAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settlement/payment-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Payment Order */
        post: operations["createPaymentOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settlement/payment-orders/{paymentOrderId}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Payment Order
         * @description Combined Dispatch/Execute step. Signals money has moved.
         */
        post: operations["executePaymentOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Account: {
            /** Format: uuid */
            accountId?: string;
            code?: string;
            name?: string;
            /** @enum {string} */
            type?: "asset" | "liability" | "equity" | "income" | "expense";
            balance?: number;
        };
        AccountCreate: {
            code: string;
            name: string;
            /** @enum {string} */
            type: "asset" | "liability" | "equity" | "income" | "expense";
        };
        JournalEntry: {
            /** Format: uuid */
            jeId?: string;
            /** @enum {string} */
            status?: "draft" | "posted" | "voided";
            /** Format: date */
            date?: string;
            lines?: {
                accountId?: string;
                debit?: number;
                credit?: number;
            }[];
        };
        JournalEntryCreate: {
            /** Format: date */
            date: string;
            memo?: string;
            lines: {
                accountId: string;
                debit?: number;
                credit?: number;
            }[];
        };
        Trust: {
            /** Format: uuid */
            trustId?: string;
            legalName?: string;
            ein?: string;
        };
        TrustCreate: {
            legalName: string;
            ein?: string;
            /** Format: date */
            dateOfTrust?: string;
            situsState?: string;
            mailingAddress?: string;
        };
        TrustUpdate: {
            mailingAddress?: string;
            /** @enum {string} */
            status?: "active" | "inactive";
        };
        Trustee: {
            /** Format: uuid */
            trusteeId?: string;
            fullName?: string;
            /** @enum {string} */
            role?: "co_trustee" | "authorized_signatory";
            independentSigningAuthority?: boolean;
            /** @enum {string} */
            status?: "active" | "inactive";
        };
        TrusteeCreate: {
            fullName: string;
            /** @enum {string} */
            role: "co_trustee" | "authorized_signatory";
            independentSigningAuthority?: boolean;
        };
        TrusteeUpdate: {
            /** @enum {string} */
            role?: "co_trustee" | "authorized_signatory";
            independentSigningAuthority?: boolean;
            /** @enum {string} */
            status?: "active" | "inactive";
        };
        AssetCreate: {
            name: string;
            /** @enum {string} */
            type: "RealProperty" | "PersonalProperty";
            value?: number;
        };
        Asset: components["schemas"]["AssetCreate"] & {
            /** Format: uuid */
            assetId?: string;
        };
        PaymentOrderCreate: {
            amount: number;
            payee: string;
            /** @enum {string} */
            method?: "WIRE" | "ACH" | "CHECK" | "LEDGER_ONLY";
        };
        PaymentOrder: components["schemas"]["PaymentOrderCreate"] & {
            /** Format: uuid */
            paymentOrderId?: string;
            /** @enum {string} */
            status?: "created" | "executed" | "failed";
        };
        ExecutionConfirmRequest: {
            transactionRef?: string;
            /** Format: date-time */
            executedAt?: string;
        };
    };
    responses: never;
    parameters: {
        TrustId: string;
        TrustIdQuery: string;
        JournalEntryId: string;
        PaymentOrderId: string;
        TrusteeId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTrusts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trust"][];
                };
            };
        };
    };
    createTrust: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrustCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trust"];
                };
            };
        };
    };
    getTrust: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trustId: components["parameters"]["TrustId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trust"];
                };
            };
        };
    };
    updateTrust: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trustId: components["parameters"]["TrustId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TrustUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trust"];
                };
            };
        };
    };
    listTrustees: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trustId: components["parameters"]["TrustId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trustee"][];
                };
            };
        };
    };
    addTrustee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trustId: components["parameters"]["TrustId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrusteeCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trustee"];
                };
            };
        };
    };
    updateTrustee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trusteeId: components["parameters"]["TrusteeId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TrusteeUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trustee"];
                };
            };
        };
    };
    listAccounts: {
        parameters: {
            query: {
                trustId: components["parameters"]["TrustIdQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
        };
    };
    createAccount: {
        parameters: {
            query: {
                trustId: components["parameters"]["TrustIdQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
        };
    };
    createJournalEntry: {
        parameters: {
            query: {
                trustId: components["parameters"]["TrustIdQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JournalEntryCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
        };
    };
    postJournalEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jeId: components["parameters"]["JournalEntryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
        };
    };
    listAssets: {
        parameters: {
            query: {
                trustId: components["parameters"]["TrustIdQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"][];
                };
            };
        };
    };
    createAsset: {
        parameters: {
            query: {
                trustId: components["parameters"]["TrustIdQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
        };
    };
    createPaymentOrder: {
        parameters: {
            query: {
                trustId: components["parameters"]["TrustIdQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentOrderCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentOrder"];
                };
            };
        };
    };
    executePaymentOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentOrderId: components["parameters"]["PaymentOrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutionConfirmRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentOrder"];
                };
            };
        };
    };
}
