apiVersion: v1
kind: Service
metadata:
  name: irs-db-postgresql
  namespace: fiduciary-system
  labels:
    app: irs-db
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
  selector:
    app: irs-db
---
apiVersion: v1
kind: Service
metadata:
  name: bso-db-postgresql
  namespace: fiduciary-system
  labels:
    app: bso-db
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
  selector:
    app: bso-db
---
apiVersion: v1
kind: Service
metadata:
  name: ledger-db-postgresql
  namespace: fiduciary-system
  labels:
    app: ledger-db
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
  selector:
    app: ledger-db
---
apiVersion: v1
kind: Service
metadata:
  name: banking-db-postgresql
  namespace: fiduciary-system
  labels:
    app: banking-db
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    targetPort: postgresql
    port: 5432
    protocol: TCP
  selector:
    app: banking-db
---
apiVersion: v1
kind: Service
metadata:
  name: audit-db-postgresql
  namespace: fiduciary-system
  labels:
    app: audit-db
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
  selector:
    app: audit-db
