apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: fiduciary-system
  labels:
    app: prometheus
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9090
    targetPort: web
    protocol: TCP
  selector:
    app: prometheus
