apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: fiduciary-system
  labels:
    app: api-gateway
    tier: frontend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app: api-gateway
