apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: fiduciary-system
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.2
          ports:
            - containerPort: 3100
              name: http-metrics
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: data
              mountPath: /tmp/loki
          args:
            - "-config.file=/etc/loki/loki.yaml"
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: data
          emptyDir: {}
